name: Domain Status Check

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-domains:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Check domains
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python Checking.py domains.csv
      
      - name: Commit updated status
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add domains.csv
          git commit -m "Update domain statuses" || exit 0
          git push
